name: Create git tag

on:
  workflow_call:
    inputs:
      tag:
        description: "Git tag"
        required: true
        type: string

jobs:
  push-git-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Push tag to GitHub if the version's tag is not tagged

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.tag }}
