name: Deployment

on:
  workflow_call:
    inputs:
      tagName:
        description: "To publish the artifact or not, default is false"
        required: true
        type: string
      artifactName:
        required: true
        type: string
        description: "Artifact name"

permissions:
  contents: read

jobs:
  deploy-to-pypi:
    name: deploy to PyPi
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      portalKeyVaultName: ${{ steps.portal.outputs.xxx }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: ~/artifact

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/