name: Versioning

on:
  workflow_call:
    outputs:
      tag_name:
        description: "The package tag name"
        value: ${{ jobs.versioning.outputs.tag_name }}
      artifact_name:
        description: "The package artifact name"
        value: ${{ jobs.versioning.outputs.artifact_name }}

jobs:
  versioning:
    name: Get tag and artifact name
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      tag_name: ${{ steps.build_tag_name.outputs.tag_name }}
      artifact_name: ${{ steps.build_artifact_name.outputs.build_name }}
    steps:
      - name: Extract branch name
        id: extract_branch  
        shell: bash
        run: echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build tag name
        id: build_tag_name
        shell: bash
        run: |
          prefix = ${{ steps.extract_branch.outputs.branch_name == 'main' && 'beta' || steps.extract_branch.outputs.branch_name }} 
          tag = ${{ format('{0}-{1}), prefix, github.run_number }}
          echo "##[set-output name=tag_name;]$(echo tag_name})"
          
      - name: Build artifact number
        id: build_artifact_name
        shell: bash
        run: |
          artifact_name = ${{ format('{0}-{1}'), 'algokit-cli', steps.build_tag_name.outputs.tag_name }}
          echo "##[set-output name=artifact_name;]$(echo artifact_name})"
      


          